### ISSUE TITLE
team_id unable to be back in null?

### ISSUE THREAD

**Issue by SageSaga** [atom-retros/atomcms#146]
After creating categories in website_teams, you can set them as team_id in users. However you are unable to remove them or insert 0 as a value to remove the user from the team.

**Comment by DennisObject** [comment]
Setting the id to be 0 or blank doesn't equal null, which is why you're having the said issue as it will try to either fetch the team with an id of 0 or blank in that case.

It's possible to fix tho by having a null check for example. I'll have a look at the issue regardless :-) 

Thanks for the report.
